dev1/p2/memory/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import patterns, url

from memory import views

urlpatterns = patterns('',
    # ex: memory/5/
    url(r'^$', views.display, name='display'),
    url(r'^(?P<mem_id>\d+)/suppr/$', views.suppr, name='suppr'),
    url(r'^(?P<mem_id>\d+)/change_priority/(?P<new_priority>\w+)/$', views.change_priority, name='change_priority'),
    url(r'^add/$', views.add, name='add'),
)

dev1/p2/memory/models.py
# -*- coding:utf-8 -*-

from django.db import models

class MemoryItem (models.Model):
    
    """Field.choices: option de Field pour définir un pré-choix"""

    #Les constantes et les valeurs courtes correspondantes à stocker"""
    MAITRISE = 'MAI'
    CONNU = 'CON'
    AREVOIR = 'AREV'
    IMPORTANT = 'IMP'
    PRIORITAIRE = 'PRIO'
    

    PRIORITY_CHOICE = (
   	# a droite, la valeur à afficher pour template (coté client) 
   	    (MAITRISE, u'Maitrisé'),
	    (CONNU, u'Connu'),
	    (AREVOIR, u'A revoir'),
	    (IMPORTANT, u'Important'),
	    (PRIORITAIRE, u'Prioritaire'),
	     )
    """Pour info, variante courte
	YEAR_IN_SCHOOL_CHOICES = (
    ('FR', 'Freshman'),
    ('SO', 'Sophomore'),
    ('JR', 'Junior'),
    ('SR', 'Senior'),
	)"""


    """Questions a poser"""



    question = models.CharField(max_length = 100)
    answer = models.CharField(max_length = 100)
    priority = models.CharField(max_length = 50, choices=PRIORITY_CHOICE,default=PRIORITAIRE)
    pub_date = models.DateTimeField(auto_now=False,auto_now_add=True)

    def __unicode__(self):
    	return self.question

dev1/p2/memory/views.py
# -*- coding:utf-8 -*-

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
import random

from memory.models import MemoryItem


def display(request):
    
    priority_scale = MemoryItem.PRIORITY_CHOICE
    # Mixed list
    mem_list = list(MemoryItem.objects.all().order_by('?'))
    item = mem_list[0]

    return render(request, 'memory/display.html',{
        'item':item,
        'priority_scale':priority_scale,
        })

def change_priority(request, mem_id, new_priority):  

    item_with_new_priority = get_object_or_404(MemoryItem, pk=mem_id)
    item_with_new_priority.priority = new_priority.encode("utf-8")
    item_with_new_priority.save()
    return HttpResponseRedirect(reverse('memory:display'))

def suppr(request, mem_id):
    
    item_to_erase = get_object_or_404(MemoryItem, pk=mem_id)
    item_to_erase.delete()
    return HttpResponseRedirect(reverse('memory:display'))

def add(request):

    item = MemoryItem()
    if request.method=='POST':
        item.question = request.POST['question'].encode("utf-8")
        item.answer = request.POST['answer'].encode("utf-8")
        priority = request.POST['priority'].encode("utf-8")

        item.save()
        return HttpResponseRedirect(reverse('memory:display'))
    return HttpResponse('erreur')

dev1/p2/memory/templates/memory/display.html
{% extends "memory/base.html" %}
{% load static %}


{% block main %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div class="container">

<h1>{{ item.question }}</h1>
<h2>{{ item.answer }}</h2>
<h2>{{ item.get_priority_display }}</h2>

<div class="row">

	<!-- x,y tuple is like MAITRISE, u"maitrisé" avec MAITRISE = MAI -->
	{% for x,y in priority_scale %}
		<!-- if the priority status of the item match the current loop in priority scale list => button should be red -->
	    {% if x == item.priority  %}
	    	<div class="col-xs-2">
	    	    <a href=""><button class="btn btn-danger">{{y}}</button></a>
	    	</div>
	    {% else %}
	        <div class="col-xs-2">
	             <a href=" {% url 'memory:change_priority' mem_id=item.id new_priority=x %}">
	            	<button class="btn btn-primary">{{y}}</button></a>
	        </div>
	    {% endif %}
	{% endfor %}
</div><br>
<div class="row">

	<div class="col-xs-8">
	    <a href="{% url 'memory:suppr' item.id %} "><button class="btn btn-danger">Supprimer</button></a>
    </div>
</div><br>

<div class="row">
    <form action="{% url 'memory:add' %}" method="post" > 

	    {% csrf_token %}
		
	    <div class="row">
		    <div class="col-xs-2">
		        <input type="text" name="question" value="mot à mémoriser">
		    </div>
		</div><br>

	    <div class="row">
		    <div class="col-xs-2">
		        <input type="text" name="answer" value="traduction">
		    </div>
	    </div><br>

		<div class="row">
		    <div class="col-xs-4">
			    <select class="form-control" name="priority" >
			        {% for x,y in priority_scale %}
			            <option>{{y}}</option>
				    {% endfor %}
			    </select>
		    </div>
	    </div><br>
        <input type="submit" value="Ajouter" class="btn btn-danger" />
    </form>
</div>

{% endblock %}