dev1/p3/articles/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import patterns, url

from articles import views

urlpatterns = patterns('',

    url(r'^all/$', views.articles, name='articles'),
    url(r'^get/(?P<article_id>\d+)/$', views.article, name='article'),
    url(r'^language/(?P<language>[a-zA-Z\-]+)/$', views.language, name='language'),
    #url(r'^(?P<article_id>\d+)/$', views.detail, name='detail'),
)

dev1/p3/p3/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'p3.views.home', name='home'),
    url(r'^articles/', include('articles.urls', namespace="articles")),
    url(r'^user_account/', include('user_account.urls', namespace="user_account")),

    url(r'^admin/', include(admin.site.urls)),
)

dev1/p3/user_account/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import patterns, url

from user_account import views

urlpatterns = patterns('',

    # login/logout
    url(r'^login/$', 'user_account.views.login'),
    url(r'^auth/$', 'user_account.views.auth_view'),
    url(r'^logout/$', 'user_account.views.logout'),
    url(r'^loggedin/$', 'user_account.views.loggedin'),
    url(r'^invalid_login/$', 'user_account.views.invalid_login'),

    # first registration
    url(r'^register_user/$', 'user_account.views.register_user'),
    url(r'^register_success/$', 'user_account.views.register_success'),
)

dev1/p3/articles/models.py
# -*- coding:utf-8 -*-

from django.db import models
from time import time



class Article (models.Model):

    title = models.CharField(max_length=200)
    body = models.TextField()
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.title




"""
def get_upload_file_name(instance,filename):
	return "uploaded_files/%s_%s"(str(time()).replace('.','_').filename)


class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    thumbnail = models.FileField(upload_to=get_upload_file_name)
    def __unicode__(self):  # Python 3: def __str__(self):
	        return self.question

"""

dev1/p3/user_account/models.py
from django.db import models

# Create your models here.

dev1/p3/user_account/forms.py
# -*- coding:utf-8 -*-

#the file is directly in the project because the registration is considered like 
# aside the application that could be developped

from django import forms
from django.contrib.auth.models import User 
from django.contrib.auth.forms import UserCreationForm


class MyRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
    	#we heritate from a model
    	model = User
    	#we chose the fields we need
    	fields = ('username', 'email', 'password1', 'password2')

    # we over write the save method of the forms.py in django file
    # search in site packages then django/contrib/auth/forms =>UserCreationForm
    def save(self, commit=True):

        user = super(UserCreationForm, self).save(commit=False)
        # we suspend the commit waiting for added datas

        # we save the password 
        user.set_password(self.cleaned_data["password1"])

        # we add the email
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user
    # in parallel we change
    # the import in the view from UserCreationForm to MyRegistrationForm
    #

dev1/p3/articles/views.py
# -*- coding:utf-8 -*-

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse

from articles.models import Article




def articles(request):
    language = 'en-gb' #in the cookie (client side)
    session_language = 'en-gb' #in the session (server side)

    if 'lang' in request.COOKIES:
        language = request.COOKIES['lang']
    
    if 'lang' in request.session:
        session_language = request.session['lang']

    return render(request, 'articles/articles.html',
    	{'articles': Article.objects.all(),
    	 'language':language,
         'session_language': session_language })



def article (request, article_id=1):

    article = get_object_or_404(Article, pk=article_id)

    return render(request, 'articles/article.html',
    	{'article':article})



def language(request, language='en-gb'):

    response = HttpResponse("setting language to %s, both session and cookies are modified" % language)
	
    #Le cookie est defini sur un objet response avec set, on appelle une action
    response.set_cookie('lang', language)

    #La session est definie sur un objet request, on définie une session
    request.session['lang'] = language

    return response

dev1/p3/user_account/views.py
# -*- coding:utf-8 -*-

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib import auth
from django.core.context_processors import csrf

from forms import MyRegistrationForm 
# replace: from django.contrib.auth.forms import UserCreationForm


def login(request):
    c={}
    c.update(csrf(request))
    return render (request, 'user_account/login.html',c)

def auth_view(request):
    username = request.POST.get('username','')
    password = request.POST.get('password','')
    user = auth.authenticate(username=username,password=password)

    if user is not None:
    	auth.login(request, user)
        return HttpResponseRedirect('/user_account/loggedin')
        """
        if user.is_active:
            print("User is valid, active and authenticated")
        else:
            print("The password is valid, but the account has been disabled!")
        """
    else:
        return HttpResponseRedirect('/user_account/invalid_login')

def loggedin(request):
	return render(request, 'user_account/loggedin.html',
		{'full_name': request.user.username})

def invalid_login(request):
	context = {}
	return render(request, 'user_account/invalid_login.html',context)

def logout(request):
    auth.logout(request)
    context = {}
    return render(request, 'user_account/logout.html', context)	

def register_user(request):
    if request.method == 'POST':
        form = MyRegistrationForm(request.POST)
        print "hello"
        if form.is_valid():
        	form.save() # YOU CAN ADD AN EMAIL CHECKIN HERE + ACCEPT CONDITIONS
        	return HttpResponseRedirect('/user_account/register_success')
    args={}
    args.update(csrf(request))
    args['form'] = MyRegistrationForm()

    print args
    return render(request, 'user_account/register.html', args)

def register_success(request):
	context ={}
	return render(request, 'user_account/register_success.html', context)

dev1/p3/articles/templates/articles/article.html
{% extends "articles/base.html" %}
{% load static %}


{% block main %}

<h2>Language set up is {{language}} </h2>

<div>
<h2><a href="{% url 'articles:article' article.id %} ">{{article.title}} </a></h2>
<p>{{article.body}} </p>
</div>

{% endblock main %}

dev1/p3/articles/templates/articles/articles.html
{% extends "articles/base.html" %}

{% block main %}
	

<h2>Language is {{language}} </h2>
<h2>Session_ Language is {{session_language}} </h2>
<h5><a href="{% url 'articles:language' language='en-GB' %}"> Change to English</a></h5>
<h5><a href="{% url 'articles:language' language='fr-FR'%}"> Change to French</a></h5>
<h5><a href="{% url 'articles:language' language='es-ES'%}"> Change to Spanish</a></h5>


{% if articles.count > 0 %}


{% for article in articles %}
<div>
<h2><a href="{% url 'articles:article' article.id %} ">{{article.title}} </a></h2>

<p>{{article.body|truncatewords:"10"}} </p>
</div>		
{% endfor %}	

{% else %}
<p>Nothing to show!</p>

{% endif %}

{% endblock main %}

dev1/p3/user_account/templates/user_account/base.html
{% load static %}

<!doctype html>
<html>
<!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>Title</title>  
    <!--  FONTS  -->
    <!-- <link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,700" rel="stylesheet" type="    text/css">
    
    <!-- Default CSS -->
    <!-- <link rel="stylesheet" href="{% static 'etudevet/css/foundation.css'%}">
    <!--[if IE 8]>
    	<link rel="stylesheet" href="{% static 'etudevet/css/ie8-grid-foundation-4.css'%}" />
    <![endif]-->
	<!--AJAX -->
    <!-- <script type="text/javascript" src="{% static "etudevet/js/ajaxsearch.js" %} "></script>
	-->
{% block css %}

    <!-- BOOTSTRAP CSS - Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
{% endblock %}

{% block js %}
{% endblock %}


</head>

<body>
     
    <!-- *************************** Header *************************** -->
    
    <div class = 'header'>
        {% block header %}
        
        {% endblock %}	
    </div>
    
    
    
    <!--*************************** Barre de Navigation ***************************-->
    
    <div class = 'nav'>
        {% block nav %}
        
        {% endblock %}	
    </div>
    

    <!-- ***************************Main Content*************************** -->

    <div class = 'main'>
        {% block main %}
        
        {% endblock %}	
    </div>
    

    
    <!-- *************************** footer ******************************  -->

    <div class = 'last'>
        {% block last %}
        
        {% endblock %}	
    </div>
    


    <footer>
        {% block footer %}
        
        {% endblock %}	
    </footer>
</body>
</html>

dev1/p3/user_account/templates/user_account/invalid_login.html
{% extends "user_account/base.html" %}

{% block main %}

<h2> Login details are INVALID, WE CALL THE POLICE NOW</h2>

{% endblock main %}

dev1/p3/user_account/templates/user_account/loggedin.html
{% extends "user_account/base.html" %}

{% block main %}

<h2> Hi {{full_name}}, you are now logged in</h2>
<p><a href="/user_account/logout/">Click here to log out</a></p>

{% endblock main %}

dev1/p3/user_account/templates/user_account/login.html
{% extends "user_account/base.html" %}

{% block main %}

    {% if form.error %}
        <p class="error"> Sorry that's not valid password or username</p>
    {% endif %}

<form action="/user_account/auth/" method="post"> {% csrf_token %}

    <label for="username">Username:</label>
    <input type="text" name="username" id="username" value="">
    <label for="password">Password:</label>
    <input type="password" name="password" id="password" value="">

    <input type="submit" value="login">

</form>

{% endblock main %}

dev1/p3/user_account/templates/user_account/logout.html
{% extends "user_account/base.html" %}

{% block main %}

<h2> You are now logged out, bye </h2>
<p><a href="/user_account/login">Me connecter</a></p>

{% endblock main %}

dev1/p3/user_account/templates/user_account/register.html
{% extends "user_account/base.html" %}

{% block main %}

<h2> Register</h2>

<!-- Trick: The form post...to itself-->
<form action="/user_account/register_user/" method ='POST'> {% csrf_token %}
{{form}}

<input type="submit" value="Register">


</form>
{% endblock main %}

dev1/p3/user_account/templates/user_account/register_success.html
{% extends "user_account/base.html" %}

{% block main %}

<h2> You have REGISTERED !</h2>

<p>Click <a href="/user_account/login/">here</a></p>


{% endblock main %}